title: "Bibian Robert"
email: "you@example.com"
description: "Geospatial Research Scientist | Data-Science | MNCAH"

# Since this will be served from the root of your user site:
baseurl: ""                      # <-- keep empty for user site
url: "https://bibian-robert.github.io"

nav:
  - { name: "About", link: "/about/" }
  - { name: "Projects", link: "/projects/" }
  - { name: "Publications", link: "/publications/" }
  - { name: "Talks", link: "/talks/" }
  - { name: "Capacity Building", link: "/capacity-building/" }
  - { name: "Community", link: "/community/" }
  - { name: "CV", link: "/cv/" }

theme: null
plugins:
  - jekyll-feed
