title: "Bibian N. Robert"
email: "you@example.com"
description: "Geospatial Research Scientist | Dataâ€‘Science | MNCAH"
baseurl: "" # for https://yourusername.github.io
url: "https://yourusername.github.io"

nav:
  - { name: "About", link: "/about/" }
  - { name: "Projects", link: "/projects/" }
  - { name: "Publications", link: "/publications/" }
  - { name: "Talks", link: "/talks/" }
  - { name: "Capacity Building", link: "/capacity-building/" }
  - { name: "Community", link: "/community/" }
  - { name: "CV", link: "/cv/" }

theme: null
plugins:
  - jekyll-feed
